INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [25/Jan/2022 18:15:56] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Jan/2022 18:15:56] "GET /static/css/main.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Jan/2022 18:15:56] "GET /favicon.ico HTTP/1.1" 404 -
INFO:app:healthz request successfull
INFO:werkzeug:127.0.0.1 - - [25/Jan/2022 18:16:17] "GET /healthz HTTP/1.1" 200 -
INFO:app:Metrics request successfull
INFO:werkzeug:127.0.0.1 - - [25/Jan/2022 18:16:36] "GET /metrics HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:app:Metrics request successfull
INFO:werkzeug:127.0.0.1 - - [25/Jan/2022 18:20:23] "GET /metrics HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:app:Metrics request successfull
INFO:werkzeug:127.0.0.1 - - [25/Jan/2022 18:22:05] "GET /metrics HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:app:Metrics request successfull
INFO:werkzeug:127.0.0.1 - - [25/Jan/2022 18:23:04] "GET /metrics HTTP/1.1" 200 -
INFO:app:Metrics request successfull
INFO:werkzeug:127.0.0.1 - - [25/Jan/2022 18:23:06] "GET /metrics HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:app:Metrics request successfull
INFO:werkzeug:127.0.0.1 - - [25/Jan/2022 18:27:09] "GET /metrics HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:app:Metrics request successfull
INFO:werkzeug:127.0.0.1 - - [25/Jan/2022 18:31:30] "GET /metrics HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
ERROR:app:Exception on /metrics [GET]
Traceback (most recent call last):
  File "/Users/lucasnovaes/Documents/cloud-native/modulo-01/nd064_course_1/project/techtrends/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/lucasnovaes/Documents/cloud-native/modulo-01/nd064_course_1/project/techtrends/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/lucasnovaes/Documents/cloud-native/modulo-01/nd064_course_1/project/techtrends/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/lucasnovaes/Documents/cloud-native/modulo-01/nd064_course_1/project/techtrends/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/lucasnovaes/Documents/cloud-native/modulo-01/nd064_course_1/project/techtrends/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/lucasnovaes/Documents/cloud-native/modulo-01/nd064_course_1/project/techtrends/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 97, in metrics
    print(os.path.exists(connection))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not sqlite3.Connection
INFO:werkzeug:127.0.0.1 - - [25/Jan/2022 18:36:13] "GET /metrics HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [25/Jan/2022 18:36:13] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [25/Jan/2022 18:36:25] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Jan/2022 18:36:25] "GET /static/css/main.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Jan/2022 18:36:31] "GET /status HTTP/1.1" 404 -
INFO:app:healthz request successfull
INFO:werkzeug:127.0.0.1 - - [25/Jan/2022 18:36:40] "GET /healthz HTTP/1.1" 200 -
ERROR:app:Exception on /metrics [GET]
Traceback (most recent call last):
  File "/Users/lucasnovaes/Documents/cloud-native/modulo-01/nd064_course_1/project/techtrends/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/lucasnovaes/Documents/cloud-native/modulo-01/nd064_course_1/project/techtrends/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/lucasnovaes/Documents/cloud-native/modulo-01/nd064_course_1/project/techtrends/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/lucasnovaes/Documents/cloud-native/modulo-01/nd064_course_1/project/techtrends/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/lucasnovaes/Documents/cloud-native/modulo-01/nd064_course_1/project/techtrends/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/lucasnovaes/Documents/cloud-native/modulo-01/nd064_course_1/project/techtrends/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 97, in metrics
    print(os.path.exists(connection))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not sqlite3.Connection
INFO:werkzeug:127.0.0.1 - - [25/Jan/2022 18:36:49] "GET /metrics HTTP/1.1" 500 -
ERROR:app:Exception on /metrics [GET]
Traceback (most recent call last):
  File "/Users/lucasnovaes/Documents/cloud-native/modulo-01/nd064_course_1/project/techtrends/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/lucasnovaes/Documents/cloud-native/modulo-01/nd064_course_1/project/techtrends/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/lucasnovaes/Documents/cloud-native/modulo-01/nd064_course_1/project/techtrends/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/lucasnovaes/Documents/cloud-native/modulo-01/nd064_course_1/project/techtrends/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/lucasnovaes/Documents/cloud-native/modulo-01/nd064_course_1/project/techtrends/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/lucasnovaes/Documents/cloud-native/modulo-01/nd064_course_1/project/techtrends/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 97, in metrics
    rows_count = connection.execute('SELECT count(*) FROM posts').fetchone()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not sqlite3.Connection
INFO:werkzeug:127.0.0.1 - - [25/Jan/2022 18:36:58] "GET /metrics HTTP/1.1" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:app:Metrics request successfull
INFO:werkzeug:127.0.0.1 - - [25/Jan/2022 18:37:07] "GET /metrics HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 940-540-536
INFO:app:Metrics request successfull
INFO:werkzeug:127.0.0.1 - - [25/Jan/2022 18:38:47] "GET /metrics HTTP/1.1" 200 -
